//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using MiAppMovil.Services; // Cambia al namespace correcto

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://service.ford.com/", ConfigurationName="WebServiceGP")]
public interface WebServiceGP
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getFiltradoPartev3Request", ReplyAction="http://service.ford.com/WebServiceGP/getFiltradoPartev3Response")]
    System.Threading.Tasks.Task<getFiltradoPartev3Response> getFiltradoPartev3Async(getFiltradoPartev3Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getFiltradoUnidadv3Request", ReplyAction="http://service.ford.com/WebServiceGP/getFiltradoUnidadv3Response")]
    System.Threading.Tasks.Task<getFiltradoUnidadv3Response> getFiltradoUnidadv3Async(getFiltradoUnidadv3Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getInfoUnidadNewv3Request", ReplyAction="http://service.ford.com/WebServiceGP/getInfoUnidadNewv3Response")]
    System.Threading.Tasks.Task<getInfoUnidadNewv3Response> getInfoUnidadNewv3Async(getInfoUnidadNewv3Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getFiltradoUnidadNewv3Request", ReplyAction="http://service.ford.com/WebServiceGP/getFiltradoUnidadNewv3Response")]
    System.Threading.Tasks.Task<getFiltradoUnidadNewv3Response> getFiltradoUnidadNewv3Async(getFiltradoUnidadNewv3Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getAccesoGerencialv3Request", ReplyAction="http://service.ford.com/WebServiceGP/getAccesoGerencialv3Response")]
    System.Threading.Tasks.Task<getAccesoGerencialv3Response> getAccesoGerencialv3Async(getAccesoGerencialv3Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getInventarioUnidadesv3Request", ReplyAction="http://service.ford.com/WebServiceGP/getInventarioUnidadesv3Response")]
    System.Threading.Tasks.Task<getInventarioUnidadesv3Response> getInventarioUnidadesv3Async(getInventarioUnidadesv3Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getInventarioUnidadesNewv3Request", ReplyAction="http://service.ford.com/WebServiceGP/getInventarioUnidadesNewv3Response")]
    System.Threading.Tasks.Task<getInventarioUnidadesNewv3Response> getInventarioUnidadesNewv3Async(getInventarioUnidadesNewv3Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getListaPreciosv3Request", ReplyAction="http://service.ford.com/WebServiceGP/getListaPreciosv3Response")]
    System.Threading.Tasks.Task<getListaPreciosv3Response> getListaPreciosv3Async(getListaPreciosv3Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getInventarioEmpresasRequest", ReplyAction="http://service.ford.com/WebServiceGP/getInventarioEmpresasResponse")]
    System.Threading.Tasks.Task<getInventarioEmpresasResponse> getInventarioEmpresasAsync(getInventarioEmpresasRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getInventarioInsertarRequest", ReplyAction="http://service.ford.com/WebServiceGP/getInventarioInsertarResponse")]
    System.Threading.Tasks.Task<getInventarioInsertarResponse> getInventarioInsertarAsync(getInventarioInsertarRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getInventarioVentasConsultarRequest", ReplyAction="http://service.ford.com/WebServiceGP/getInventarioVentasConsultarResponse")]
    System.Threading.Tasks.Task<getInventarioVentasConsultarResponse> getInventarioVentasConsultarAsync(getInventarioVentasConsultarRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getInventarioVentasInsertarRequest", ReplyAction="http://service.ford.com/WebServiceGP/getInventarioVentasInsertarResponse")]
    System.Threading.Tasks.Task<getInventarioVentasInsertarResponse> getInventarioVentasInsertarAsync(getInventarioVentasInsertarRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getConsultaReporteFordRequest", ReplyAction="http://service.ford.com/WebServiceGP/getConsultaReporteFordResponse")]
    System.Threading.Tasks.Task<getConsultaReporteFordResponse> getConsultaReporteFordAsync(getConsultaReporteFordRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getConsultaQueryReporteFordRequest", ReplyAction="http://service.ford.com/WebServiceGP/getConsultaQueryReporteFordResponse")]
    System.Threading.Tasks.Task<getConsultaQueryReporteFordResponse> getConsultaQueryReporteFordAsync(getConsultaQueryReporteFordRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getConsultaOrdenServicioRequest", ReplyAction="http://service.ford.com/WebServiceGP/getConsultaOrdenServicioResponse")]
    System.Threading.Tasks.Task<getConsultaOrdenServicioResponse> getConsultaOrdenServicioAsync(getConsultaOrdenServicioRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getInsertaDatosaQuiterRequest", ReplyAction="http://service.ford.com/WebServiceGP/getInsertaDatosaQuiterResponse")]
    System.Threading.Tasks.Task<getInsertaDatosaQuiterResponse> getInsertaDatosaQuiterAsync(getInsertaDatosaQuiterRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/PruebaRefugioReporteRequest", ReplyAction="http://service.ford.com/WebServiceGP/PruebaRefugioReporteResponse")]
    System.Threading.Tasks.Task<PruebaRefugioReporteResponse> PruebaRefugioReporteAsync(PruebaRefugioReporteRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getInfoPartev3Request", ReplyAction="http://service.ford.com/WebServiceGP/getInfoPartev3Response")]
    System.Threading.Tasks.Task<getInfoPartev3Response> getInfoPartev3Async(getInfoPartev3Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getInfoUnidadv3Request", ReplyAction="http://service.ford.com/WebServiceGP/getInfoUnidadv3Response")]
    System.Threading.Tasks.Task<getInfoUnidadv3Response> getInfoUnidadv3Async(getInfoUnidadv3Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://service.ford.com/WebServiceGP/getAccesoGeneralRequest", ReplyAction="http://service.ford.com/WebServiceGP/getAccesoGeneralResponse")]
    System.Threading.Tasks.Task<getAccesoGeneralResponse> getAccesoGeneralAsync(getAccesoGeneralRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getFiltradoPartev3Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getFiltradoPartev3", Namespace="http://service.ford.com/", Order=0)]
    public getFiltradoPartev3RequestBody Body;
    
    public getFiltradoPartev3Request()
    {
    }
    
    public getFiltradoPartev3Request(getFiltradoPartev3RequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getFiltradoPartev3RequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string semiparte;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string empresa;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string id;
    
    public getFiltradoPartev3RequestBody()
    {
    }
    
    public getFiltradoPartev3RequestBody(string semiparte, string empresa, string id)
    {
        this.semiparte = semiparte;
        this.empresa = empresa;
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getFiltradoPartev3Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getFiltradoPartev3Response", Namespace="http://service.ford.com/", Order=0)]
    public getFiltradoPartev3ResponseBody Body;
    
    public getFiltradoPartev3Response()
    {
    }
    
    public getFiltradoPartev3Response(getFiltradoPartev3ResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getFiltradoPartev3ResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getFiltradoPartev3ResponseBody()
    {
    }
    
    public getFiltradoPartev3ResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getFiltradoUnidadv3Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getFiltradoUnidadv3", Namespace="http://service.ford.com/", Order=0)]
    public getFiltradoUnidadv3RequestBody Body;
    
    public getFiltradoUnidadv3Request()
    {
    }
    
    public getFiltradoUnidadv3Request(getFiltradoUnidadv3RequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getFiltradoUnidadv3RequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string catalogo;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string empresa;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string opcion;
    
    public getFiltradoUnidadv3RequestBody()
    {
    }
    
    public getFiltradoUnidadv3RequestBody(string catalogo, string empresa, string id, string opcion)
    {
        this.catalogo = catalogo;
        this.empresa = empresa;
        this.id = id;
        this.opcion = opcion;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getFiltradoUnidadv3Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getFiltradoUnidadv3Response", Namespace="http://service.ford.com/", Order=0)]
    public getFiltradoUnidadv3ResponseBody Body;
    
    public getFiltradoUnidadv3Response()
    {
    }
    
    public getFiltradoUnidadv3Response(getFiltradoUnidadv3ResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getFiltradoUnidadv3ResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getFiltradoUnidadv3ResponseBody()
    {
    }
    
    public getFiltradoUnidadv3ResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInfoUnidadNewv3Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoUnidadNewv3", Namespace="http://service.ford.com/", Order=0)]
    public getInfoUnidadNewv3RequestBody Body;
    
    public getInfoUnidadNewv3Request()
    {
    }
    
    public getInfoUnidadNewv3Request(getInfoUnidadNewv3RequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInfoUnidadNewv3RequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string catalogo;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string empresa;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string demo;
    
    public getInfoUnidadNewv3RequestBody()
    {
    }
    
    public getInfoUnidadNewv3RequestBody(string catalogo, string empresa, string id, string demo)
    {
        this.catalogo = catalogo;
        this.empresa = empresa;
        this.id = id;
        this.demo = demo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInfoUnidadNewv3Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoUnidadNewv3Response", Namespace="http://service.ford.com/", Order=0)]
    public getInfoUnidadNewv3ResponseBody Body;
    
    public getInfoUnidadNewv3Response()
    {
    }
    
    public getInfoUnidadNewv3Response(getInfoUnidadNewv3ResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInfoUnidadNewv3ResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getInfoUnidadNewv3ResponseBody()
    {
    }
    
    public getInfoUnidadNewv3ResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getFiltradoUnidadNewv3Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getFiltradoUnidadNewv3", Namespace="http://service.ford.com/", Order=0)]
    public getFiltradoUnidadNewv3RequestBody Body;
    
    public getFiltradoUnidadNewv3Request()
    {
    }
    
    public getFiltradoUnidadNewv3Request(getFiltradoUnidadNewv3RequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getFiltradoUnidadNewv3RequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string catalogo;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string empresa;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string opcion;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string demo;
    
    public getFiltradoUnidadNewv3RequestBody()
    {
    }
    
    public getFiltradoUnidadNewv3RequestBody(string catalogo, string empresa, string id, string opcion, string demo)
    {
        this.catalogo = catalogo;
        this.empresa = empresa;
        this.id = id;
        this.opcion = opcion;
        this.demo = demo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getFiltradoUnidadNewv3Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getFiltradoUnidadNewv3Response", Namespace="http://service.ford.com/", Order=0)]
    public getFiltradoUnidadNewv3ResponseBody Body;
    
    public getFiltradoUnidadNewv3Response()
    {
    }
    
    public getFiltradoUnidadNewv3Response(getFiltradoUnidadNewv3ResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getFiltradoUnidadNewv3ResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getFiltradoUnidadNewv3ResponseBody()
    {
    }
    
    public getFiltradoUnidadNewv3ResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getAccesoGerencialv3Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getAccesoGerencialv3", Namespace="http://service.ford.com/", Order=0)]
    public getAccesoGerencialv3RequestBody Body;
    
    public getAccesoGerencialv3Request()
    {
    }
    
    public getAccesoGerencialv3Request(getAccesoGerencialv3RequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getAccesoGerencialv3RequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string id;
    
    public getAccesoGerencialv3RequestBody()
    {
    }
    
    public getAccesoGerencialv3RequestBody(string id)
    {
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getAccesoGerencialv3Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getAccesoGerencialv3Response", Namespace="http://service.ford.com/", Order=0)]
    public getAccesoGerencialv3ResponseBody Body;
    
    public getAccesoGerencialv3Response()
    {
    }
    
    public getAccesoGerencialv3Response(getAccesoGerencialv3ResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getAccesoGerencialv3ResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getAccesoGerencialv3ResponseBody()
    {
    }
    
    public getAccesoGerencialv3ResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioUnidadesv3Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioUnidadesv3", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioUnidadesv3RequestBody Body;
    
    public getInventarioUnidadesv3Request()
    {
    }
    
    public getInventarioUnidadesv3Request(getInventarioUnidadesv3RequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioUnidadesv3RequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string empresa;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string id;
    
    public getInventarioUnidadesv3RequestBody()
    {
    }
    
    public getInventarioUnidadesv3RequestBody(string empresa, string id)
    {
        this.empresa = empresa;
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioUnidadesv3Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioUnidadesv3Response", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioUnidadesv3ResponseBody Body;
    
    public getInventarioUnidadesv3Response()
    {
    }
    
    public getInventarioUnidadesv3Response(getInventarioUnidadesv3ResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioUnidadesv3ResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getInventarioUnidadesv3ResponseBody()
    {
    }
    
    public getInventarioUnidadesv3ResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioUnidadesNewv3Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioUnidadesNewv3", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioUnidadesNewv3RequestBody Body;
    
    public getInventarioUnidadesNewv3Request()
    {
    }
    
    public getInventarioUnidadesNewv3Request(getInventarioUnidadesNewv3RequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioUnidadesNewv3RequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string empresa;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string demo;
    
    public getInventarioUnidadesNewv3RequestBody()
    {
    }
    
    public getInventarioUnidadesNewv3RequestBody(string empresa, string id, string demo)
    {
        this.empresa = empresa;
        this.id = id;
        this.demo = demo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioUnidadesNewv3Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioUnidadesNewv3Response", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioUnidadesNewv3ResponseBody Body;
    
    public getInventarioUnidadesNewv3Response()
    {
    }
    
    public getInventarioUnidadesNewv3Response(getInventarioUnidadesNewv3ResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioUnidadesNewv3ResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getInventarioUnidadesNewv3ResponseBody()
    {
    }
    
    public getInventarioUnidadesNewv3ResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getListaPreciosv3Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getListaPreciosv3", Namespace="http://service.ford.com/", Order=0)]
    public getListaPreciosv3RequestBody Body;
    
    public getListaPreciosv3Request()
    {
    }
    
    public getListaPreciosv3Request(getListaPreciosv3RequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getListaPreciosv3RequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string empresa;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string unidad;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string id;
    
    public getListaPreciosv3RequestBody()
    {
    }
    
    public getListaPreciosv3RequestBody(string empresa, string unidad, string id)
    {
        this.empresa = empresa;
        this.unidad = unidad;
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getListaPreciosv3Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getListaPreciosv3Response", Namespace="http://service.ford.com/", Order=0)]
    public getListaPreciosv3ResponseBody Body;
    
    public getListaPreciosv3Response()
    {
    }
    
    public getListaPreciosv3Response(getListaPreciosv3ResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getListaPreciosv3ResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getListaPreciosv3ResponseBody()
    {
    }
    
    public getListaPreciosv3ResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioEmpresasRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioEmpresas", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioEmpresasRequestBody Body;
    
    public getInventarioEmpresasRequest()
    {
    }
    
    public getInventarioEmpresasRequest(getInventarioEmpresasRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioEmpresasRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string area;
    
    public getInventarioEmpresasRequestBody()
    {
    }
    
    public getInventarioEmpresasRequestBody(string id, string area)
    {
        this.id = id;
        this.area = area;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioEmpresasResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioEmpresasResponse", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioEmpresasResponseBody Body;
    
    public getInventarioEmpresasResponse()
    {
    }
    
    public getInventarioEmpresasResponse(getInventarioEmpresasResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioEmpresasResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getInventarioEmpresasResponseBody()
    {
    }
    
    public getInventarioEmpresasResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioInsertarRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioInsertar", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioInsertarRequestBody Body;
    
    public getInventarioInsertarRequest()
    {
    }
    
    public getInventarioInsertarRequest(getInventarioInsertarRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioInsertarRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string inventario;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string usuario;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string parte;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string contenedor;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string contenedorid;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
    public string anaquel;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
    public string cajon;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
    public string cantidad;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
    public string observacion;
    
    public getInventarioInsertarRequestBody()
    {
    }
    
    public getInventarioInsertarRequestBody(string id, string inventario, string usuario, string parte, string contenedor, string contenedorid, string anaquel, string cajon, string cantidad, string observacion)
    {
        this.id = id;
        this.inventario = inventario;
        this.usuario = usuario;
        this.parte = parte;
        this.contenedor = contenedor;
        this.contenedorid = contenedorid;
        this.anaquel = anaquel;
        this.cajon = cajon;
        this.cantidad = cantidad;
        this.observacion = observacion;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioInsertarResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioInsertarResponse", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioInsertarResponseBody Body;
    
    public getInventarioInsertarResponse()
    {
    }
    
    public getInventarioInsertarResponse(getInventarioInsertarResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioInsertarResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getInventarioInsertarResponseBody()
    {
    }
    
    public getInventarioInsertarResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioVentasConsultarRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioVentasConsultar", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioVentasConsultarRequestBody Body;
    
    public getInventarioVentasConsultarRequest()
    {
    }
    
    public getInventarioVentasConsultarRequest(getInventarioVentasConsultarRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioVentasConsultarRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string nuevo;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string vin;
    
    public getInventarioVentasConsultarRequestBody()
    {
    }
    
    public getInventarioVentasConsultarRequestBody(string id, string nuevo, string vin)
    {
        this.id = id;
        this.nuevo = nuevo;
        this.vin = vin;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioVentasConsultarResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioVentasConsultarResponse", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioVentasConsultarResponseBody Body;
    
    public getInventarioVentasConsultarResponse()
    {
    }
    
    public getInventarioVentasConsultarResponse(getInventarioVentasConsultarResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioVentasConsultarResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getInventarioVentasConsultarResponseBody()
    {
    }
    
    public getInventarioVentasConsultarResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioVentasInsertarRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioVentasInsertar", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioVentasInsertarRequestBody Body;
    
    public getInventarioVentasInsertarRequest()
    {
    }
    
    public getInventarioVentasInsertarRequest(getInventarioVentasInsertarRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioVentasInsertarRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string inventario;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string usuario;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string idv;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string ubicacion;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string observacion;
    
    public getInventarioVentasInsertarRequestBody()
    {
    }
    
    public getInventarioVentasInsertarRequestBody(string id, string inventario, string usuario, string idv, string ubicacion, string observacion)
    {
        this.id = id;
        this.inventario = inventario;
        this.usuario = usuario;
        this.idv = idv;
        this.ubicacion = ubicacion;
        this.observacion = observacion;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInventarioVentasInsertarResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInventarioVentasInsertarResponse", Namespace="http://service.ford.com/", Order=0)]
    public getInventarioVentasInsertarResponseBody Body;
    
    public getInventarioVentasInsertarResponse()
    {
    }
    
    public getInventarioVentasInsertarResponse(getInventarioVentasInsertarResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInventarioVentasInsertarResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getInventarioVentasInsertarResponseBody()
    {
    }
    
    public getInventarioVentasInsertarResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getConsultaReporteFordRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getConsultaReporteFord", Namespace="http://service.ford.com/", Order=0)]
    public getConsultaReporteFordRequestBody Body;
    
    public getConsultaReporteFordRequest()
    {
    }
    
    public getConsultaReporteFordRequest(getConsultaReporteFordRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getConsultaReporteFordRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string usuario;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string almacen;
    
    public getConsultaReporteFordRequestBody()
    {
    }
    
    public getConsultaReporteFordRequestBody(string usuario, string almacen)
    {
        this.usuario = usuario;
        this.almacen = almacen;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getConsultaReporteFordResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getConsultaReporteFordResponse", Namespace="http://service.ford.com/", Order=0)]
    public getConsultaReporteFordResponseBody Body;
    
    public getConsultaReporteFordResponse()
    {
    }
    
    public getConsultaReporteFordResponse(getConsultaReporteFordResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getConsultaReporteFordResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getConsultaReporteFordResponseBody()
    {
    }
    
    public getConsultaReporteFordResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getConsultaQueryReporteFordRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getConsultaQueryReporteFord", Namespace="http://service.ford.com/", Order=0)]
    public getConsultaQueryReporteFordRequestBody Body;
    
    public getConsultaQueryReporteFordRequest()
    {
    }
    
    public getConsultaQueryReporteFordRequest(getConsultaQueryReporteFordRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getConsultaQueryReporteFordRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string usuario;
    
    public getConsultaQueryReporteFordRequestBody()
    {
    }
    
    public getConsultaQueryReporteFordRequestBody(string usuario)
    {
        this.usuario = usuario;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getConsultaQueryReporteFordResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getConsultaQueryReporteFordResponse", Namespace="http://service.ford.com/", Order=0)]
    public getConsultaQueryReporteFordResponseBody Body;
    
    public getConsultaQueryReporteFordResponse()
    {
    }
    
    public getConsultaQueryReporteFordResponse(getConsultaQueryReporteFordResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getConsultaQueryReporteFordResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getConsultaQueryReporteFordResponseBody()
    {
    }
    
    public getConsultaQueryReporteFordResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getConsultaOrdenServicioRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getConsultaOrdenServicio", Namespace="http://service.ford.com/", Order=0)]
    public getConsultaOrdenServicioRequestBody Body;
    
    public getConsultaOrdenServicioRequest()
    {
    }
    
    public getConsultaOrdenServicioRequest(getConsultaOrdenServicioRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getConsultaOrdenServicioRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string taller;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string referencia;
    
    public getConsultaOrdenServicioRequestBody()
    {
    }
    
    public getConsultaOrdenServicioRequestBody(string taller, string referencia)
    {
        this.taller = taller;
        this.referencia = referencia;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getConsultaOrdenServicioResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getConsultaOrdenServicioResponse", Namespace="http://service.ford.com/", Order=0)]
    public getConsultaOrdenServicioResponseBody Body;
    
    public getConsultaOrdenServicioResponse()
    {
    }
    
    public getConsultaOrdenServicioResponse(getConsultaOrdenServicioResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getConsultaOrdenServicioResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getConsultaOrdenServicioResponseBody()
    {
    }
    
    public getConsultaOrdenServicioResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInsertaDatosaQuiterRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInsertaDatosaQuiter", Namespace="http://service.ford.com/", Order=0)]
    public getInsertaDatosaQuiterRequestBody Body;
    
    public getInsertaDatosaQuiterRequest()
    {
    }
    
    public getInsertaDatosaQuiterRequest(getInsertaDatosaQuiterRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInsertaDatosaQuiterRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string taller;
    
    public getInsertaDatosaQuiterRequestBody()
    {
    }
    
    public getInsertaDatosaQuiterRequestBody(string taller)
    {
        this.taller = taller;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInsertaDatosaQuiterResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInsertaDatosaQuiterResponse", Namespace="http://service.ford.com/", Order=0)]
    public getInsertaDatosaQuiterResponseBody Body;
    
    public getInsertaDatosaQuiterResponse()
    {
    }
    
    public getInsertaDatosaQuiterResponse(getInsertaDatosaQuiterResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInsertaDatosaQuiterResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getInsertaDatosaQuiterResponseBody()
    {
    }
    
    public getInsertaDatosaQuiterResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class PruebaRefugioReporteRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="PruebaRefugioReporte", Namespace="http://service.ford.com/", Order=0)]
    public PruebaRefugioReporteRequestBody Body;
    
    public PruebaRefugioReporteRequest()
    {
    }
    
    public PruebaRefugioReporteRequest(PruebaRefugioReporteRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class PruebaRefugioReporteRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string taller;
    
    public PruebaRefugioReporteRequestBody()
    {
    }
    
    public PruebaRefugioReporteRequestBody(string taller)
    {
        this.taller = taller;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class PruebaRefugioReporteResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="PruebaRefugioReporteResponse", Namespace="http://service.ford.com/", Order=0)]
    public PruebaRefugioReporteResponseBody Body;
    
    public PruebaRefugioReporteResponse()
    {
    }
    
    public PruebaRefugioReporteResponse(PruebaRefugioReporteResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class PruebaRefugioReporteResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public PruebaRefugioReporteResponseBody()
    {
    }
    
    public PruebaRefugioReporteResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInfoPartev3Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoPartev3", Namespace="http://service.ford.com/", Order=0)]
    public getInfoPartev3RequestBody Body;
    
    public getInfoPartev3Request()
    {
    }
    
    public getInfoPartev3Request(getInfoPartev3RequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInfoPartev3RequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string parte;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string empresa;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string id;
    
    public getInfoPartev3RequestBody()
    {
    }
    
    public getInfoPartev3RequestBody(string parte, string empresa, string id)
    {
        this.parte = parte;
        this.empresa = empresa;
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInfoPartev3Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoPartev3Response", Namespace="http://service.ford.com/", Order=0)]
    public getInfoPartev3ResponseBody Body;
    
    public getInfoPartev3Response()
    {
    }
    
    public getInfoPartev3Response(getInfoPartev3ResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInfoPartev3ResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getInfoPartev3ResponseBody()
    {
    }
    
    public getInfoPartev3ResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInfoUnidadv3Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoUnidadv3", Namespace="http://service.ford.com/", Order=0)]
    public getInfoUnidadv3RequestBody Body;
    
    public getInfoUnidadv3Request()
    {
    }
    
    public getInfoUnidadv3Request(getInfoUnidadv3RequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInfoUnidadv3RequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string catalogo;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string empresa;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string id;
    
    public getInfoUnidadv3RequestBody()
    {
    }
    
    public getInfoUnidadv3RequestBody(string catalogo, string empresa, string id)
    {
        this.catalogo = catalogo;
        this.empresa = empresa;
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getInfoUnidadv3Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoUnidadv3Response", Namespace="http://service.ford.com/", Order=0)]
    public getInfoUnidadv3ResponseBody Body;
    
    public getInfoUnidadv3Response()
    {
    }
    
    public getInfoUnidadv3Response(getInfoUnidadv3ResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getInfoUnidadv3ResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getInfoUnidadv3ResponseBody()
    {
    }
    
    public getInfoUnidadv3ResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getAccesoGeneralRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getAccesoGeneral", Namespace="http://service.ford.com/", Order=0)]
    public getAccesoGeneralRequestBody Body;
    
    public getAccesoGeneralRequest()
    {
    }
    
    public getAccesoGeneralRequest(getAccesoGeneralRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getAccesoGeneralRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string area;
    
    public getAccesoGeneralRequestBody()
    {
    }
    
    public getAccesoGeneralRequestBody(string id, string area)
    {
        this.id = id;
        this.area = area;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getAccesoGeneralResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="getAccesoGeneralResponse", Namespace="http://service.ford.com/", Order=0)]
    public getAccesoGeneralResponseBody Body;
    
    public getAccesoGeneralResponse()
    {
    }
    
    public getAccesoGeneralResponse(getAccesoGeneralResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="")]
public partial class getAccesoGeneralResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string @return;
    
    public getAccesoGeneralResponseBody()
    {
    }
    
    public getAccesoGeneralResponseBody(string @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public interface WebServiceGPChannel : WebServiceGP, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public partial class WebServiceGPClient : System.ServiceModel.ClientBase<WebServiceGP>, WebServiceGP
{
    
    /// <summary>
    /// Implemente este método parcial para configurar el punto de conexión de servicio.
    /// </summary>
    /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
    /// <param name="clientCredentials">Credenciales de cliente</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public WebServiceGPClient() : 
            base(WebServiceGPClient.GetDefaultBinding(), WebServiceGPClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.WebServiceGPPort.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WebServiceGPClient(EndpointConfiguration endpointConfiguration) : 
            base(WebServiceGPClient.GetBindingForEndpoint(endpointConfiguration), WebServiceGPClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WebServiceGPClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(WebServiceGPClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WebServiceGPClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(WebServiceGPClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WebServiceGPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getFiltradoPartev3Response> WebServiceGP.getFiltradoPartev3Async(getFiltradoPartev3Request request)
    {
        return base.Channel.getFiltradoPartev3Async(request);
    }
    
    public System.Threading.Tasks.Task<getFiltradoPartev3Response> getFiltradoPartev3Async(string semiparte, string empresa, string id)
    {
        getFiltradoPartev3Request inValue = new getFiltradoPartev3Request();
        inValue.Body = new getFiltradoPartev3RequestBody();
        inValue.Body.semiparte = semiparte;
        inValue.Body.empresa = empresa;
        inValue.Body.id = id;
        return ((WebServiceGP)(this)).getFiltradoPartev3Async(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getFiltradoUnidadv3Response> WebServiceGP.getFiltradoUnidadv3Async(getFiltradoUnidadv3Request request)
    {
        return base.Channel.getFiltradoUnidadv3Async(request);
    }
    
    public System.Threading.Tasks.Task<getFiltradoUnidadv3Response> getFiltradoUnidadv3Async(string catalogo, string empresa, string id, string opcion)
    {
        getFiltradoUnidadv3Request inValue = new getFiltradoUnidadv3Request();
        inValue.Body = new getFiltradoUnidadv3RequestBody();
        inValue.Body.catalogo = catalogo;
        inValue.Body.empresa = empresa;
        inValue.Body.id = id;
        inValue.Body.opcion = opcion;
        return ((WebServiceGP)(this)).getFiltradoUnidadv3Async(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getInfoUnidadNewv3Response> WebServiceGP.getInfoUnidadNewv3Async(getInfoUnidadNewv3Request request)
    {
        return base.Channel.getInfoUnidadNewv3Async(request);
    }
    
    public System.Threading.Tasks.Task<getInfoUnidadNewv3Response> getInfoUnidadNewv3Async(string catalogo, string empresa, string id, string demo)
    {
        getInfoUnidadNewv3Request inValue = new getInfoUnidadNewv3Request();
        inValue.Body = new getInfoUnidadNewv3RequestBody();
        inValue.Body.catalogo = catalogo;
        inValue.Body.empresa = empresa;
        inValue.Body.id = id;
        inValue.Body.demo = demo;
        return ((WebServiceGP)(this)).getInfoUnidadNewv3Async(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getFiltradoUnidadNewv3Response> WebServiceGP.getFiltradoUnidadNewv3Async(getFiltradoUnidadNewv3Request request)
    {
        return base.Channel.getFiltradoUnidadNewv3Async(request);
    }
    
    public System.Threading.Tasks.Task<getFiltradoUnidadNewv3Response> getFiltradoUnidadNewv3Async(string catalogo, string empresa, string id, string opcion, string demo)
    {
        getFiltradoUnidadNewv3Request inValue = new getFiltradoUnidadNewv3Request();
        inValue.Body = new getFiltradoUnidadNewv3RequestBody();
        inValue.Body.catalogo = catalogo;
        inValue.Body.empresa = empresa;
        inValue.Body.id = id;
        inValue.Body.opcion = opcion;
        inValue.Body.demo = demo;
        return ((WebServiceGP)(this)).getFiltradoUnidadNewv3Async(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getAccesoGerencialv3Response> WebServiceGP.getAccesoGerencialv3Async(getAccesoGerencialv3Request request)
    {
        return base.Channel.getAccesoGerencialv3Async(request);
    }
    
    public System.Threading.Tasks.Task<getAccesoGerencialv3Response> getAccesoGerencialv3Async(string id)
    {
        getAccesoGerencialv3Request inValue = new getAccesoGerencialv3Request();
        inValue.Body = new getAccesoGerencialv3RequestBody();
        inValue.Body.id = id;
        return ((WebServiceGP)(this)).getAccesoGerencialv3Async(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getInventarioUnidadesv3Response> WebServiceGP.getInventarioUnidadesv3Async(getInventarioUnidadesv3Request request)
    {
        return base.Channel.getInventarioUnidadesv3Async(request);
    }
    
    public System.Threading.Tasks.Task<getInventarioUnidadesv3Response> getInventarioUnidadesv3Async(string empresa, string id)
    {
        getInventarioUnidadesv3Request inValue = new getInventarioUnidadesv3Request();
        inValue.Body = new getInventarioUnidadesv3RequestBody();
        inValue.Body.empresa = empresa;
        inValue.Body.id = id;
        return ((WebServiceGP)(this)).getInventarioUnidadesv3Async(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getInventarioUnidadesNewv3Response> WebServiceGP.getInventarioUnidadesNewv3Async(getInventarioUnidadesNewv3Request request)
    {
        return base.Channel.getInventarioUnidadesNewv3Async(request);
    }
    
    public System.Threading.Tasks.Task<getInventarioUnidadesNewv3Response> getInventarioUnidadesNewv3Async(string empresa, string id, string demo)
    {
        getInventarioUnidadesNewv3Request inValue = new getInventarioUnidadesNewv3Request();
        inValue.Body = new getInventarioUnidadesNewv3RequestBody();
        inValue.Body.empresa = empresa;
        inValue.Body.id = id;
        inValue.Body.demo = demo;
        return ((WebServiceGP)(this)).getInventarioUnidadesNewv3Async(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getListaPreciosv3Response> WebServiceGP.getListaPreciosv3Async(getListaPreciosv3Request request)
    {
        return base.Channel.getListaPreciosv3Async(request);
    }
    
    public System.Threading.Tasks.Task<getListaPreciosv3Response> getListaPreciosv3Async(string empresa, string unidad, string id)
    {
        getListaPreciosv3Request inValue = new getListaPreciosv3Request();
        inValue.Body = new getListaPreciosv3RequestBody();
        inValue.Body.empresa = empresa;
        inValue.Body.unidad = unidad;
        inValue.Body.id = id;
        return ((WebServiceGP)(this)).getListaPreciosv3Async(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getInventarioEmpresasResponse> WebServiceGP.getInventarioEmpresasAsync(getInventarioEmpresasRequest request)
    {
        return base.Channel.getInventarioEmpresasAsync(request);
    }
    
    public System.Threading.Tasks.Task<getInventarioEmpresasResponse> getInventarioEmpresasAsync(string id, string area)
    {
        getInventarioEmpresasRequest inValue = new getInventarioEmpresasRequest();
        inValue.Body = new getInventarioEmpresasRequestBody();
        inValue.Body.id = id;
        inValue.Body.area = area;
        return ((WebServiceGP)(this)).getInventarioEmpresasAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getInventarioInsertarResponse> WebServiceGP.getInventarioInsertarAsync(getInventarioInsertarRequest request)
    {
        return base.Channel.getInventarioInsertarAsync(request);
    }
    
    public System.Threading.Tasks.Task<getInventarioInsertarResponse> getInventarioInsertarAsync(string id, string inventario, string usuario, string parte, string contenedor, string contenedorid, string anaquel, string cajon, string cantidad, string observacion)
    {
        getInventarioInsertarRequest inValue = new getInventarioInsertarRequest();
        inValue.Body = new getInventarioInsertarRequestBody();
        inValue.Body.id = id;
        inValue.Body.inventario = inventario;
        inValue.Body.usuario = usuario;
        inValue.Body.parte = parte;
        inValue.Body.contenedor = contenedor;
        inValue.Body.contenedorid = contenedorid;
        inValue.Body.anaquel = anaquel;
        inValue.Body.cajon = cajon;
        inValue.Body.cantidad = cantidad;
        inValue.Body.observacion = observacion;
        return ((WebServiceGP)(this)).getInventarioInsertarAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getInventarioVentasConsultarResponse> WebServiceGP.getInventarioVentasConsultarAsync(getInventarioVentasConsultarRequest request)
    {
        return base.Channel.getInventarioVentasConsultarAsync(request);
    }
    
    public System.Threading.Tasks.Task<getInventarioVentasConsultarResponse> getInventarioVentasConsultarAsync(string id, string nuevo, string vin)
    {
        getInventarioVentasConsultarRequest inValue = new getInventarioVentasConsultarRequest();
        inValue.Body = new getInventarioVentasConsultarRequestBody();
        inValue.Body.id = id;
        inValue.Body.nuevo = nuevo;
        inValue.Body.vin = vin;
        return ((WebServiceGP)(this)).getInventarioVentasConsultarAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getInventarioVentasInsertarResponse> WebServiceGP.getInventarioVentasInsertarAsync(getInventarioVentasInsertarRequest request)
    {
        return base.Channel.getInventarioVentasInsertarAsync(request);
    }
    
    public System.Threading.Tasks.Task<getInventarioVentasInsertarResponse> getInventarioVentasInsertarAsync(string id, string inventario, string usuario, string idv, string ubicacion, string observacion)
    {
        getInventarioVentasInsertarRequest inValue = new getInventarioVentasInsertarRequest();
        inValue.Body = new getInventarioVentasInsertarRequestBody();
        inValue.Body.id = id;
        inValue.Body.inventario = inventario;
        inValue.Body.usuario = usuario;
        inValue.Body.idv = idv;
        inValue.Body.ubicacion = ubicacion;
        inValue.Body.observacion = observacion;
        return ((WebServiceGP)(this)).getInventarioVentasInsertarAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getConsultaReporteFordResponse> WebServiceGP.getConsultaReporteFordAsync(getConsultaReporteFordRequest request)
    {
        return base.Channel.getConsultaReporteFordAsync(request);
    }
    
    public System.Threading.Tasks.Task<getConsultaReporteFordResponse> getConsultaReporteFordAsync(string usuario, string almacen)
    {
        getConsultaReporteFordRequest inValue = new getConsultaReporteFordRequest();
        inValue.Body = new getConsultaReporteFordRequestBody();
        inValue.Body.usuario = usuario;
        inValue.Body.almacen = almacen;
        return ((WebServiceGP)(this)).getConsultaReporteFordAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getConsultaQueryReporteFordResponse> WebServiceGP.getConsultaQueryReporteFordAsync(getConsultaQueryReporteFordRequest request)
    {
        return base.Channel.getConsultaQueryReporteFordAsync(request);
    }
    
    public System.Threading.Tasks.Task<getConsultaQueryReporteFordResponse> getConsultaQueryReporteFordAsync(string usuario)
    {
        getConsultaQueryReporteFordRequest inValue = new getConsultaQueryReporteFordRequest();
        inValue.Body = new getConsultaQueryReporteFordRequestBody();
        inValue.Body.usuario = usuario;
        return ((WebServiceGP)(this)).getConsultaQueryReporteFordAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getConsultaOrdenServicioResponse> WebServiceGP.getConsultaOrdenServicioAsync(getConsultaOrdenServicioRequest request)
    {
        return base.Channel.getConsultaOrdenServicioAsync(request);
    }
    
    public System.Threading.Tasks.Task<getConsultaOrdenServicioResponse> getConsultaOrdenServicioAsync(string taller, string referencia)
    {
        getConsultaOrdenServicioRequest inValue = new getConsultaOrdenServicioRequest();
        inValue.Body = new getConsultaOrdenServicioRequestBody();
        inValue.Body.taller = taller;
        inValue.Body.referencia = referencia;
        return ((WebServiceGP)(this)).getConsultaOrdenServicioAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getInsertaDatosaQuiterResponse> WebServiceGP.getInsertaDatosaQuiterAsync(getInsertaDatosaQuiterRequest request)
    {
        return base.Channel.getInsertaDatosaQuiterAsync(request);
    }
    
    public System.Threading.Tasks.Task<getInsertaDatosaQuiterResponse> getInsertaDatosaQuiterAsync(string taller)
    {
        getInsertaDatosaQuiterRequest inValue = new getInsertaDatosaQuiterRequest();
        inValue.Body = new getInsertaDatosaQuiterRequestBody();
        inValue.Body.taller = taller;
        return ((WebServiceGP)(this)).getInsertaDatosaQuiterAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<PruebaRefugioReporteResponse> WebServiceGP.PruebaRefugioReporteAsync(PruebaRefugioReporteRequest request)
    {
        return base.Channel.PruebaRefugioReporteAsync(request);
    }
    
    public System.Threading.Tasks.Task<PruebaRefugioReporteResponse> PruebaRefugioReporteAsync(string taller)
    {
        PruebaRefugioReporteRequest inValue = new PruebaRefugioReporteRequest();
        inValue.Body = new PruebaRefugioReporteRequestBody();
        inValue.Body.taller = taller;
        return ((WebServiceGP)(this)).PruebaRefugioReporteAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getInfoPartev3Response> WebServiceGP.getInfoPartev3Async(getInfoPartev3Request request)
    {
        return base.Channel.getInfoPartev3Async(request);
    }
    
    public System.Threading.Tasks.Task<getInfoPartev3Response> getInfoPartev3Async(string parte, string empresa, string id)
    {
        getInfoPartev3Request inValue = new getInfoPartev3Request();
        inValue.Body = new getInfoPartev3RequestBody();
        inValue.Body.parte = parte;
        inValue.Body.empresa = empresa;
        inValue.Body.id = id;
        return ((WebServiceGP)(this)).getInfoPartev3Async(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getInfoUnidadv3Response> WebServiceGP.getInfoUnidadv3Async(getInfoUnidadv3Request request)
    {
        return base.Channel.getInfoUnidadv3Async(request);
    }
    
    public System.Threading.Tasks.Task<getInfoUnidadv3Response> getInfoUnidadv3Async(string catalogo, string empresa, string id)
    {
        getInfoUnidadv3Request inValue = new getInfoUnidadv3Request();
        inValue.Body = new getInfoUnidadv3RequestBody();
        inValue.Body.catalogo = catalogo;
        inValue.Body.empresa = empresa;
        inValue.Body.id = id;
        return ((WebServiceGP)(this)).getInfoUnidadv3Async(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getAccesoGeneralResponse> WebServiceGP.getAccesoGeneralAsync(getAccesoGeneralRequest request)
    {
        return base.Channel.getAccesoGeneralAsync(request);
    }
    
    public System.Threading.Tasks.Task<getAccesoGeneralResponse> getAccesoGeneralAsync(string id, string area)
    {
        getAccesoGeneralRequest inValue = new getAccesoGeneralRequest();
        inValue.Body = new getAccesoGeneralRequestBody();
        inValue.Body.id = id;
        inValue.Body.area = area;
        return ((WebServiceGP)(this)).getAccesoGeneralAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    #if !NET6_0_OR_GREATER
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    #endif
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.WebServiceGPPort))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.WebServiceGPPort))
        {
            return new System.ServiceModel.EndpointAddress("https://fordsureste.mx/WSRefacciones/WebServiceGP");
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return WebServiceGPClient.GetBindingForEndpoint(EndpointConfiguration.WebServiceGPPort);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return WebServiceGPClient.GetEndpointAddress(EndpointConfiguration.WebServiceGPPort);
    }
    
    public enum EndpointConfiguration
    {
        
        WebServiceGPPort,
    }
}
